# Generated by Django 4.2.19 on 2025-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
